CREATE TABLE Kursy (
	KursID INT IDENTITY(10,1) PRIMARY KEY,
	Nazwa_Kursu VARCHAR(60) NOT NULL,
	ECTS INT NOT NULL
	);

CREATE TABLE Studenci (
	StudentID INT IDENTITY(1,1) PRIMARY KEY,
	Imie VARCHAR(30) NOT NULL,
	Nazwisko VARCHAR(30) NOT NULL,
	Rok_Studiow INT NOT NULL
	);

CREATE TABLE Zapisy (
	ZapisID INT IDENTITY(100,1) PRIMARY KEY,
	StudentID INT,
	FOREIGN KEY (StudentID) REFERENCES Studenci(StudentID),
	KursID INT,
	FOREIGN KEY (KursID) REFERENCES Kursy(KursID),
	Data_Zapisu Date NOT NULL
	);